name = "MittagLeffler"
uuid = "9c257583-4f8f-53fd-abd9-c69d5080dd54"
license = "MIT"
version = "1.0.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
QuadGK = "2"
SpecialFunctions = "0.7, 0.10, 1.5, 2"
julia = "1"
Test = ">= 0.0"
Aqua = ">= 0.8"
JET = ">= 0.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
